### ISSUE TITLE
"connect, register and quit, securely"-test fails

### ISSUE THREAD

**Issue by f0x52** [matrix-org/node-irc#38]
I thought this was a fault in my forked changes, but tests were already failing before I touched anything...
```
⨯ connect, register and quit, securely
  not ok 27 Client sent NICK message
    ---
      operator: equal
      expected: |-
        'NICK testbot'
      actual: |-
        'QUIT :node-irc says goodbye'
      at: MockIrcd.<anonymous> (/home/f0x/shared/documents/projects/node-irc/test/test-irc.js:63:15)
      stack: |-
        Error: Client sent NICK message
            at Test.assert [as _assert] (/home/f0x/shared/documents/projects/node-irc/node_modules/tape/lib/test.js:225:54)
            at Test.bound [as _assert] (/home/f0x/shared/documents/projects/node-irc/node_modules/tape/lib/test.js:77:32)
            at Test.equal (/home/f0x/shared/documents/projects/node-irc/node_modules/tape/lib/test.js:385:10)
            at Test.bound [as equal] (/home/f0x/shared/documents/projects/node-irc/node_modules/tape/lib/test.js:77:32)
            at MockIrcd.<anonymous> (/home/f0x/shared/documents/projects/node-irc/test/test-irc.js:63:15)
            at MockIrcd.emit (events.js:210:5)
            at TLSSocket.<anonymous> (/home/f0x/shared/documents/projects/node-irc/test/helpers.js:42:18)
            at TLSSocket.emit (events.js:215:7)
            at endReadableNT (_stream_readable.js:1183:12)
            at processTicksAndRejections (internal/process/task_queues.js:80:21)
    ...
  13 Oct 14:18:26 - Connection got "end" event
  13 Oct 14:18:26 - Connection got "close" event
```

**Comment by Half-Shot** [comment]
this was because the cert included in the test had expired. Have created a new one and wacked up the expiry date by many years.
